version: '3.8'

services:
  postgres:
    image: postgres:16.2  # Imagen de PostgreSQL
    restart: always  # Reiniciar automáticamente si falla
    environment:
      POSTGRES_DB: ${DB_DATABASE}  # Nombre de la base de datos
      POSTGRES_USER: ${DB_USERNAME}  # Nombre de usuario
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Contraseña
    ports:
      - '15432:5432'  # Exponer el puerto de PostgreSQL para conexión local
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistencia de datos

  pgadmin:
    image: dpage/pgadmin4  # Imagen de pgAdmin
    restart: always  # Reiniciar automáticamente si falla
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.org"  # Email de acceso a pgAdmin
      PGADMIN_DEFAULT_PASSWORD: "admin"  # Contraseña de acceso a pgAdmin
    ports:
      - '8081:80'  # Exponer pgAdmin en el puerto 8081
    depends_on:
      - postgres  # Esperar a que PostgreSQL esté disponible

volumes:
  postgres-data:  # Volumen persistente para los datos de PostgreSQL
