version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:8080'
    depends_on:
      - postgres
    environment:
      # POSTGRES DATABASE
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_SYNC: ${DB_SYNC}

    volumes:
      - .:/app
      - /app/node_modules
    command: |
      yarn start:dev && \
      echo "API is accessible at http://localhost:${PORT}"

  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '15432:5432' # Cambia el puerto si es necesario
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - '8081:80' # Cambia el puerto si es necesario
    depends_on:
      - postgres

volumes:
  postgres-data:


networks:
  default:
    driver: bridge
